name: 03 - Workflow Runners


on: workflow_dispatch


jobs:
    ubunto-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: |
                echo "This job is running on an Ubuntu runner"
                echo "Runner OS: $RUNNER_OS"

    windows-echo:
        runs-on: windows-latest
        steps:
            - name: Show OS
              shell: bash
              run: |
                echo "This job runs on Windows"
                echo "Runner OS: $RUNNER_OS"
    
    mac-echo:
        runs-on: macos-latest
        steps:
            - name: Show OS
              run: |
                echo "This job runs on Mac OS"
                echo "Runner OS: $RUNNER_OS"